name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [13, 12]
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: zilder/pg-ext-check

    steps:
      - run: pg-setup ${{ matrix.pg }}
      - run: apt-get install liblz4-dev libzstd-dev
      - uses: actions/checkout@v2
      - run: build-check
